apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gitclone
spec:
  description: >-
    This task can be used to perform git operation.
    For example to git clone from git server use token
  workspaces:
    - name: repo
      mountPath: /workspace/repo
  params:
    - name: url
  steps:
    - name: gitclone
      image: public.ecr.aws/docker/library/maven:3.9.4-amazoncorretto-17
      workingDir: /workspace/repo
      script: |
        mvn -v
        yum install git -y
        git clone $(params.url)
        mvn clean package -DskipTests -Dcheckstyle.skip -f spring-petclinic/pom.xml