apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: gitclonepipelinerun
spec:
  workspaces:
    - name: pipeline-ws
      volumeClaimTemplate:
        metadata:
          name: gitclone-pvc
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  pipelineRef:
    name: gitclonepipeline
