apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-goodbye-final
spec:
  params:
  - name: username
    type: string
  - name: commit
    description: git commit
  - name: message
    description: git message
  tasks:
    - name: hello
      taskRef:
        name: hello
    - name: goodbye
      runAfter:
        - hello
      taskRef:
        name: goodbye
      params:
      - name: username
        value: $(params.username)
    - name: final
      runAfter:
        - goodbye
      taskRef:
        name: final
      params:
      - name: message
        value: $(params.message)
      - name: commit
        value: $(params.commit)
